### ISSUE TITLE
Error when running random_pick.yaml

### ISSUE THREAD

**Issue by lyc-king** [intel/ros2_grasp_library#82]
Environment: Ubuntu 18.04+ROS2 dashing+UR5

I modified some data in random_pick.yaml according to our lab's setup after finishing handeye calibration for attached camera amounted on the end effector. However, it unexpectedly went wrong when running random_pick.yaml showing the error as follows:

`ros2 run grasp_ros2 grasp_ros2 __params:=src/ros2_grasp_library/grasp_ros2/cfg/random_pick.yaml`

**terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to parse parameters from file 'src/ros2_grasp_library/grasp_ros2/cfg/random_pick.yaml': Error parsing a event near line 10, at /tmp/binarydeb/ros-dashing-rcl-yaml-param-parser-0.7.9/src/parser.c:1213**

I'd appreciate it a lot if anyone can give any suggestions. Thank you so much!

**Comment by lyc-king** [comment]
My .yaml file is like this:

```
GraspDetectorGPD:
  ros__parameters:
    cloud_topic: /camera/pointcloud  # Name of point cloud topic as input to the grasp detection
    rviz: true
    device: 0 # 0:CPU, 1:GPU, 2:VPU
    auto_mode: false  # Configure to service-driven mode and it should be "false"
    plane_remove: true # Enabling this helps to avoid generating grasp poses across the table
    # object_detect: false
    # grasp workspace in camera frames!!!
    # workspace: [-0.18, 0.18, -0.25, 0.05, 0.0, 1.0]  #Modified by LYC--fixed beside robot
	workspace: [0, 0.60, -0.3, 0.3, -0.3, 0.3]  #Modified by LYC--attached on robot

    # gripper geometry parameters in metre ########### Modified to current gripper! LYC
    finger_width: 0.01 # the finger thickness
    hand_outer_diameter: 0.12 # the maximum robot hand aperture 
    hand_depth: 0.085  # the hand depth (the finger length)
    hand_height: 0.01 # the finger breadth

GraspPlanner:
  ros__parameters:
    grasp_score_threshold: 1 # Minimum score expected for grasps returned from this service.
    grasp_frame_id: "base" # Frame id expected for grasps returned from this service.
    grasp_approach: [0.0, 0.0, -1.0] # expect approaching in -z axis
    grasp_approach_angle: 0.345 # 1.047=PI/3 # 0.785=PI/4 # 0.523=PI/6 # 0.345=PI/9 # acceptable approaching angle
    grasp_offset: [0.02, 0.01, -0.05] #Offset [x, y, z] in metres applied to the grasps detected. unit: meter

    # grasp boundry in grasp_frame_id
    grasp_boundry: [-0.3, 0.3, 0.0, 1.0, 0.1, 1.0] # Boundry cube in grasp_frame_id expected for grasps returned from this service.
    eef_offset: 0.14 # Offset in metres from the gripper base (finger root) to the parent link of gripper. 
    eef_yaw_offset: 0.0  # Gripper yaw offset to its parent link, in radian. Attention_Double!
    finger_joint_names: ["panda_finger_joint1", "panda_finger_joint2"] # Joint names of gripper fingers.
```
